### ISSUE TITLE
Agent returns same console return value while no additional output is given

### ISSUE THREAD

**Issue by inureyes** [lablup/sorna-agent#37]
* Agent returns same console return value while no additional output is given
 * It should be blank if output is not given from kernel 

 * Images:

![screen shot 2017-05-30 at 11 18 31 am](https://cloud.githubusercontent.com/assets/949915/26565947/655c8bfa-452a-11e7-93da-06e44efb3430.png)

These two XHR response should be different. (value of "console" key should be blank in second image)

![screen shot 2017-05-30 at 11 18 33 am](https://cloud.githubusercontent.com/assets/949915/26565953/68d2dafa-452a-11e7-90de-7abbd793c14d.png)

**Comment by adrysn** [comment]
This turns out to be a frontend problem. Refer to https://github.com/lablup/neumann/issues/802.
